# Generated by Django 5.2.17 on 2026-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('canceled', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_checkout_session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_customer_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
