# Generated by Django 5.2.17 on 2026-09-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
