# Generated by Django 5.2.17 on 2026-08-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='Gym',
        ),
    ]
