# Generated by Django 5.2.17 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
