# Generated by Django 5.2.17 on 2026-09-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-member_since',)},
        ),
    ]
